
package xyz.stasiak.beanssoapservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-21T19:27:41.652+02:00
 * Generated source version: 4.0.5
 *
 */
public final class BeansSoapService_BeansSoapServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://beanssoapservice.stasiak.xyz/", "BeansSoapServiceService");

    private BeansSoapService_BeansSoapServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BeansSoapServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BeansSoapServiceService ss = new BeansSoapServiceService(wsdlURL, SERVICE_NAME);
        BeansSoapService port = ss.getBeansSoapServicePort();

        {
        System.out.println("Invoking grindBeans...");
        xyz.stasiak.beanssoapservice.BeansSoapGrindRequest _grindBeans_arg0 = new xyz.stasiak.beanssoapservice.BeansSoapGrindRequest();
        try {
            xyz.stasiak.beanssoapservice.BeansSoapGrindResponse _grindBeans__return = port.grindBeans(_grindBeans_arg0);
            System.out.println("grindBeans.result=" + _grindBeans__return);

        } catch (BeansSoapException_Exception e) {
            System.out.println("Expected exception: BeansSoapException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking cancelBeans...");
        xyz.stasiak.beanssoapservice.BeansSoapCancelRequest _cancelBeans_arg0 = new xyz.stasiak.beanssoapservice.BeansSoapCancelRequest();
        xyz.stasiak.beanssoapservice.BeansSoapCancelResponse _cancelBeans__return = port.cancelBeans(_cancelBeans_arg0);
        System.out.println("cancelBeans.result=" + _cancelBeans__return);


        }

        System.exit(0);
    }

}
