
package xyz.stasiak.beanssoapservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-21T19:27:41.696+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "BeansSoapException", targetNamespace = "http://beanssoapservice.stasiak.xyz/")
public class BeansSoapException_Exception extends Exception {

    private xyz.stasiak.beanssoapservice.BeansSoapException faultInfo;

    public BeansSoapException_Exception() {
        super();
    }

    public BeansSoapException_Exception(String message) {
        super(message);
    }

    public BeansSoapException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BeansSoapException_Exception(String message, xyz.stasiak.beanssoapservice.BeansSoapException beansSoapException) {
        super(message);
        this.faultInfo = beansSoapException;
    }

    public BeansSoapException_Exception(String message, xyz.stasiak.beanssoapservice.BeansSoapException beansSoapException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = beansSoapException;
    }

    public xyz.stasiak.beanssoapservice.BeansSoapException getFaultInfo() {
        return this.faultInfo;
    }
}
