package xyz.stasiak.beanssoapservice;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-21T19:27:41.710+02:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "BeansSoapServiceService",
                  wsdlLocation = "http://beans-soap-service:8082/soap-api/service/beans?wsdl",
                  targetNamespace = "http://beanssoapservice.stasiak.xyz/")
public class BeansSoapServiceService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://beanssoapservice.stasiak.xyz/", "BeansSoapServiceService");
    public static final QName BeansSoapServicePort = new QName("http://beanssoapservice.stasiak.xyz/", "BeansSoapServicePort");
    static {
        URL url = null;
        try {
            url = URI.create("http://beans-soap-service:8082/soap-api/service/beans?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BeansSoapServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://beans-soap-service:8082/soap-api/service/beans?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BeansSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BeansSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BeansSoapServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BeansSoapServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BeansSoapServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BeansSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BeansSoapService
     */
    @WebEndpoint(name = "BeansSoapServicePort")
    public BeansSoapService getBeansSoapServicePort() {
        return super.getPort(BeansSoapServicePort, BeansSoapService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BeansSoapService
     */
    @WebEndpoint(name = "BeansSoapServicePort")
    public BeansSoapService getBeansSoapServicePort(WebServiceFeature... features) {
        return super.getPort(BeansSoapServicePort, BeansSoapService.class, features);
    }

}
