package xyz.stasiak.beanssoapservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-21T19:27:41.704+02:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://beanssoapservice.stasiak.xyz/", name = "BeansSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface BeansSoapService {

    @WebMethod
    @RequestWrapper(localName = "grindBeans", targetNamespace = "http://beanssoapservice.stasiak.xyz/", className = "xyz.stasiak.beanssoapservice.GrindBeans")
    @ResponseWrapper(localName = "grindBeansResponse", targetNamespace = "http://beanssoapservice.stasiak.xyz/", className = "xyz.stasiak.beanssoapservice.GrindBeansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public xyz.stasiak.beanssoapservice.BeansSoapGrindResponse grindBeans(

        @WebParam(name = "arg0", targetNamespace = "")
        xyz.stasiak.beanssoapservice.BeansSoapGrindRequest arg0
    ) throws BeansSoapException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cancelBeans", targetNamespace = "http://beanssoapservice.stasiak.xyz/", className = "xyz.stasiak.beanssoapservice.CancelBeans")
    @ResponseWrapper(localName = "cancelBeansResponse", targetNamespace = "http://beanssoapservice.stasiak.xyz/", className = "xyz.stasiak.beanssoapservice.CancelBeansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public xyz.stasiak.beanssoapservice.BeansSoapCancelResponse cancelBeans(

        @WebParam(name = "arg0", targetNamespace = "")
        xyz.stasiak.beanssoapservice.BeansSoapCancelRequest arg0
    );
}
